export const FETCH_LOGIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_LOGIN_FAILS = 'FETCH_SIGNIN_FAILS'
export const FETCH_LOGIN_BEGIN = 'FETCH_SIGNIN_BEGIN'

export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS'
export const FETCH_SIGNUP_FAILS = 'FETCH_SIGNUP_FAILS'
export const FETCH_SIGNUP_BEGIN = 'FETCH_SIGNUP_BEGIN'

export const FETCH_SIGNOUT_SUCCESS = 'FETCH_SIGNOUT_SUCCESS'