export const FETCH_LOGIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_LOGIN_FAILS = 'FETCH_SIGNIN_FAILS'
export const FETCH_LOGIN_BEGIN = 'FETCH_SIGNIN_BEGIN'

export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS'
export const FETCH_SIGNUP_FAILS = 'FETCH_SIGNUP_FAILS'
export const FETCH_SIGNUP_BEGIN = 'FETCH_SIGNUP_BEGIN'

export const CHATS_SUCCESS = 'CHATS_SUCCESS'
export const CHATS_FAILS = 'CHATS_FAILS'
export const CHATS_BEGIN = 'CHATS_BEGIN'
export const CHATS_ADD_OUT = 'CHATS_ADD_OUT'

export const PLAYERS_SUCCESS = 'PLAYERS_SUCCESS'
export const PLAYERS_FAILS = 'PLAYERS_FAILS'
export const PLAYERS_BEGIN = 'PLAYERS_BEGIN'

export const SPEC_PLAYERS_SUCCESS = 'SPEC_PLAYERS_SUCCESS'
export const SPEC_PLAYERS_FAILS = 'SPEC_PLAYERS_FAILS'
export const SPEC_PLAYERS_BEGIN = 'SPEC_PLAYERS_BEGIN'

export const FETCH_SIGNOUT_SUCCESS = 'FETCH_SIGNOUT_SUCCESS'

export const MESSAGING_USERS = 'MESSAGING_USERS'

export const CHATROOM_SUCCESS = 'CHATROOM_SUCCESS'
export const CHATROOM_FAILS = 'CHATROOM_FAILS'
export const CHATROOM_BEGIN = 'CHATROOM_BEGIN'
